import { Student } from '../app/interfaces';

export const STUDENTS: Student[] = [
  {
    id: 1,
    firstName: 'Liam',
    lastName: 'Smith',
    email: 'liam.smith@example.com',
    gender: 'Male',
    dateOfBirth: '2005-04-12',
    grade: 12,
    major: 'Science',
    enrollmentDate: '2021-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 86,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 79,
        completed: true,
      },
    ],
  },
  {
    id: 2,
    firstName: 'Emma',
    lastName: 'Johnson',
    email: 'emma.johnson@example.com',
    gender: 'Female',
    dateOfBirth: '2006-02-20',
    grade: 11,
    major: 'Arts',
    enrollmentDate: '2022-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 87,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 97,
        completed: true,
      },
    ],
  },
  {
    id: 3,
    firstName: 'Noah',
    lastName: 'Williams',
    email: 'noah.williams@example.com',
    gender: 'Male',
    dateOfBirth: '2004-10-15',
    grade: 12,
    major: 'Math',
    enrollmentDate: '2021-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 86,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 83,
        completed: false,
      },
    ],
  },
  {
    id: 4,
    firstName: 'Olivia',
    lastName: 'Brown',
    email: 'olivia.brown@example.com',
    gender: 'Female',
    dateOfBirth: '2007-06-03',
    grade: 10,
    major: 'History',
    enrollmentDate: '2023-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 75,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 82,
        completed: true,
      },
    ],
  },
  {
    id: 5,
    firstName: 'James',
    lastName: 'Jones',
    email: 'james.jones@example.com',
    gender: 'Male',
    dateOfBirth: '2005-08-21',
    grade: 12,
    major: 'Computer Science',
    enrollmentDate: '2021-09-01',
    isActive: false,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 73,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 92,
        completed: false,
      },
    ],
  },
  {
    id: 6,
    firstName: 'Ava',
    lastName: 'Garcia',
    email: 'ava.garcia@example.com',
    gender: 'Female',
    dateOfBirth: '2006-01-14',
    grade: 11,
    major: 'Biology',
    enrollmentDate: '2022-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 99,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 83,
        completed: false,
      },
    ],
  },
  {
    id: 7,
    firstName: 'Elijah',
    lastName: 'Martinez',
    email: 'elijah.martinez@example.com',
    gender: 'Male',
    dateOfBirth: '2007-11-30',
    grade: 10,
    major: 'Geography',
    enrollmentDate: '2023-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 71,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 88,
        completed: false,
      },
    ],
  },
  {
    id: 8,
    firstName: 'Sophia',
    lastName: 'Davis',
    email: 'sophia.davis@example.com',
    gender: 'Female',
    dateOfBirth: '2005-05-25',
    grade: 12,
    major: 'Physics',
    enrollmentDate: '2021-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 70,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 91,
        completed: true,
      },
    ],
  },
  {
    id: 9,
    firstName: 'Lucas',
    lastName: 'Rodriguez',
    email: 'lucas.rodriguez@example.com',
    gender: 'Male',
    dateOfBirth: '2006-09-13',
    grade: 11,
    major: 'Chemistry',
    enrollmentDate: '2022-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 92,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 71,
        completed: true,
      },
    ],
  },
  {
    id: 10,
    firstName: 'Isabella',
    lastName: 'Miller',
    email: 'isabella.miller@example.com',
    gender: 'Female',
    dateOfBirth: '2004-03-02',
    grade: 12,
    major: 'Literature',
    enrollmentDate: '2021-09-01',
    isActive: false,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 82,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 92,
        completed: false,
      },
    ],
  },
  {
    id: 11,
    firstName: 'Mason',
    lastName: 'Hernandez',
    email: 'mason.hernandez@example.com',
    gender: 'Male',
    dateOfBirth: '2005-07-09',
    grade: 12,
    major: 'Engineering',
    enrollmentDate: '2021-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 86,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 81,
        completed: false,
      },
    ],
  },
  {
    id: 12,
    firstName: 'Mia',
    lastName: 'Lopez',
    email: 'mia.lopez@example.com',
    gender: 'Female',
    dateOfBirth: '2006-04-17',
    grade: 11,
    major: 'Math',
    enrollmentDate: '2022-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 78,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 73,
        completed: true,
      },
    ],
  },
  {
    id: 13,
    firstName: 'Ethan',
    lastName: 'Gonzalez',
    email: 'ethan.gonzalez@example.com',
    gender: 'Male',
    dateOfBirth: '2007-08-19',
    grade: 10,
    major: 'Science',
    enrollmentDate: '2023-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 77,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 93,
        completed: true,
      },
    ],
  },
  {
    id: 14,
    firstName: 'Charlotte',
    lastName: 'Wilson',
    email: 'charlotte.wilson@example.com',
    gender: 'Female',
    dateOfBirth: '2006-12-08',
    grade: 11,
    major: 'Computer Science',
    enrollmentDate: '2022-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 97,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 74,
        completed: false,
      },
    ],
  },
  {
    id: 15,
    firstName: 'Logan',
    lastName: 'Anderson',
    email: 'logan.anderson@example.com',
    gender: 'Male',
    dateOfBirth: '2005-06-11',
    grade: 12,
    major: 'History',
    enrollmentDate: '2021-09-01',
    isActive: false,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 91,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 73,
        completed: false,
      },
    ],
  },
  {
    id: 16,
    firstName: 'Amelia',
    lastName: 'Thomas',
    email: 'amelia.thomas@example.com',
    gender: 'Female',
    dateOfBirth: '2007-10-07',
    grade: 10,
    major: 'Biology',
    enrollmentDate: '2023-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 77,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 73,
        completed: false,
      },
    ],
  },
  {
    id: 17,
    firstName: 'Aiden',
    lastName: 'Taylor',
    email: 'aiden.taylor@example.com',
    gender: 'Male',
    dateOfBirth: '2006-05-22',
    grade: 11,
    major: 'Geography',
    enrollmentDate: '2022-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 70,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 82,
        completed: false,
      },
    ],
  },
  {
    id: 18,
    firstName: 'Harper',
    lastName: 'Moore',
    email: 'harper.moore@example.com',
    gender: 'Female',
    dateOfBirth: '2005-02-03',
    grade: 12,
    major: 'Arts',
    enrollmentDate: '2021-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 93,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 94,
        completed: true,
      },
    ],
  },
  {
    id: 19,
    firstName: 'Jackson',
    lastName: 'Jackson',
    email: 'jackson.jackson@example.com',
    gender: 'Male',
    dateOfBirth: '2007-03-15',
    grade: 10,
    major: 'Math',
    enrollmentDate: '2023-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 83,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 92,
        completed: true,
      },
    ],
  },
  {
    id: 20,
    firstName: 'Evelyn',
    lastName: 'Martin',
    email: 'evelyn.martin@example.com',
    gender: 'Female',
    dateOfBirth: '2006-11-23',
    grade: 11,
    major: 'Science',
    enrollmentDate: '2022-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 87,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 79,
        completed: false,
      },
    ],
  },
  {
    id: 21,
    firstName: 'Sebastian',
    lastName: 'Lee',
    email: 'sebastian.lee@example.com',
    gender: 'Male',
    dateOfBirth: '2005-09-01',
    grade: 12,
    major: 'Literature',
    enrollmentDate: '2021-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 95,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 85,
        completed: false,
      },
    ],
  },
  {
    id: 22,
    firstName: 'Aria',
    lastName: 'Perez',
    email: 'aria.perez@example.com',
    gender: 'Female',
    dateOfBirth: '2004-12-18',
    grade: 12,
    major: 'Physics',
    enrollmentDate: '2021-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 79,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 70,
        completed: false,
      },
    ],
  },
  {
    id: 23,
    firstName: 'Matthew',
    lastName: 'White',
    email: 'matthew.white@example.com',
    gender: 'Male',
    dateOfBirth: '2006-07-14',
    grade: 11,
    major: 'Chemistry',
    enrollmentDate: '2022-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 96,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 88,
        completed: true,
      },
    ],
  },
  {
    id: 24,
    firstName: 'Ella',
    lastName: 'Harris',
    email: 'ella.harris@example.com',
    gender: 'Female',
    dateOfBirth: '2007-01-30',
    grade: 10,
    major: 'Engineering',
    enrollmentDate: '2023-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 75,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 83,
        completed: true,
      },
    ],
  },
  {
    id: 25,
    firstName: 'Henry',
    lastName: 'Clark',
    email: 'henry.clark@example.com',
    gender: 'Male',
    dateOfBirth: '2005-10-10',
    grade: 12,
    major: 'Arts',
    enrollmentDate: '2021-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 92,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 71,
        completed: false,
      },
    ],
  },
  {
    id: 26,
    firstName: 'Chloe',
    lastName: 'Lewis',
    email: 'chloe.lewis@example.com',
    gender: 'Female',
    dateOfBirth: '2006-03-05',
    grade: 11,
    major: 'Computer Science',
    enrollmentDate: '2022-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 99,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 79,
        completed: false,
      },
    ],
  },
  {
    id: 27,
    firstName: 'Daniel',
    lastName: 'Robinson',
    email: 'daniel.robinson@example.com',
    gender: 'Male',
    dateOfBirth: '2007-06-21',
    grade: 10,
    major: 'Science',
    enrollmentDate: '2023-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 85,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 98,
        completed: false,
      },
    ],
  },
  {
    id: 28,
    firstName: 'Grace',
    lastName: 'Walker',
    email: 'grace.walker@example.com',
    gender: 'Female',
    dateOfBirth: '2005-11-12',
    grade: 12,
    major: 'Biology',
    enrollmentDate: '2021-09-01',
    isActive: false,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 86,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 79,
        completed: true,
      },
    ],
  },
  {
    id: 29,
    firstName: 'Wyatt',
    lastName: 'Young',
    email: 'wyatt.young@example.com',
    gender: 'Male',
    dateOfBirth: '2006-08-06',
    grade: 11,
    major: 'Math',
    enrollmentDate: '2022-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 88,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 84,
        completed: false,
      },
    ],
  },
  {
    id: 30,
    firstName: 'Scarlett',
    lastName: 'Allen',
    email: 'scarlett.allen@example.com',
    gender: 'Female',
    dateOfBirth: '2007-09-27',
    grade: 10,
    major: 'History',
    enrollmentDate: '2023-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 87,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 90,
        completed: true,
      },
    ],
  },
  {
    id: 31,
    firstName: 'Jack',
    lastName: 'King',
    email: 'jack.king@example.com',
    gender: 'Male',
    dateOfBirth: '2005-03-09',
    grade: 12,
    major: 'Geography',
    enrollmentDate: '2021-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 98,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 91,
        completed: true,
      },
    ],
  },
  {
    id: 32,
    firstName: 'Luna',
    lastName: 'Wright',
    email: 'luna.wright@example.com',
    gender: 'Female',
    dateOfBirth: '2006-10-19',
    grade: 11,
    major: 'Science',
    enrollmentDate: '2022-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 79,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 81,
        completed: true,
      },
    ],
  },
  {
    id: 33,
    firstName: 'Owen',
    lastName: 'Scott',
    email: 'owen.scott@example.com',
    gender: 'Male',
    dateOfBirth: '2007-05-03',
    grade: 10,
    major: 'Math',
    enrollmentDate: '2023-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 81,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 73,
        completed: false,
      },
    ],
  },
  {
    id: 34,
    firstName: 'Layla',
    lastName: 'Torres',
    email: 'layla.torres@example.com',
    gender: 'Female',
    dateOfBirth: '2004-06-26',
    grade: 12,
    major: 'Engineering',
    enrollmentDate: '2021-09-01',
    isActive: false,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 73,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 95,
        completed: true,
      },
    ],
  },
  {
    id: 35,
    firstName: 'Gabriel',
    lastName: 'Nguyen',
    email: 'gabriel.nguyen@example.com',
    gender: 'Male',
    dateOfBirth: '2006-01-16',
    grade: 11,
    major: 'Literature',
    enrollmentDate: '2022-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 86,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 94,
        completed: true,
      },
    ],
  },
  {
    id: 36,
    firstName: 'Hannah',
    lastName: 'Hill',
    email: 'hannah.hill@example.com',
    gender: 'Female',
    dateOfBirth: '2005-12-02',
    grade: 12,
    major: 'Arts',
    enrollmentDate: '2021-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 88,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 84,
        completed: false,
      },
    ],
  },
  {
    id: 37,
    firstName: 'Carter',
    lastName: 'Flores',
    email: 'carter.flores@example.com',
    gender: 'Male',
    dateOfBirth: '2007-07-07',
    grade: 10,
    major: 'Computer Science',
    enrollmentDate: '2023-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 73,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 81,
        completed: false,
      },
    ],
  },
  {
    id: 38,
    firstName: 'Zoe',
    lastName: 'Green',
    email: 'zoe.green@example.com',
    gender: 'Female',
    dateOfBirth: '2006-09-08',
    grade: 11,
    major: 'Physics',
    enrollmentDate: '2022-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 93,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 85,
        completed: true,
      },
    ],
  },
  {
    id: 39,
    firstName: 'Isaac',
    lastName: 'Adams',
    email: 'isaac.adams@example.com',
    gender: 'Male',
    dateOfBirth: '2005-04-04',
    grade: 12,
    major: 'Science',
    enrollmentDate: '2021-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 94,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 97,
        completed: false,
      },
    ],
  },
  {
    id: 40,
    firstName: 'Victoria',
    lastName: 'Nelson',
    email: 'victoria.nelson@example.com',
    gender: 'Female',
    dateOfBirth: '2007-03-13',
    grade: 10,
    major: 'Biology',
    enrollmentDate: '2023-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 99,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 84,
        completed: true,
      },
    ],
  },
  {
    id: 41,
    firstName: 'Julian',
    lastName: 'Baker',
    email: 'julian.baker@example.com',
    gender: 'Male',
    dateOfBirth: '2006-02-01',
    grade: 11,
    major: 'Math',
    enrollmentDate: '2022-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 73,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 72,
        completed: false,
      },
    ],
  },
  {
    id: 42,
    firstName: 'Penelope',
    lastName: 'Rivera',
    email: 'penelope.rivera@example.com',
    gender: 'Female',
    dateOfBirth: '2005-11-11',
    grade: 12,
    major: 'History',
    enrollmentDate: '2021-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 92,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 76,
        completed: true,
      },
    ],
  },
  {
    id: 43,
    firstName: 'Levi',
    lastName: 'Campbell',
    email: 'levi.campbell@example.com',
    gender: 'Male',
    dateOfBirth: '2007-10-02',
    grade: 10,
    major: 'Science',
    enrollmentDate: '2023-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 77,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 86,
        completed: false,
      },
    ],
  },
  {
    id: 44,
    firstName: 'Nora',
    lastName: 'Mitchell',
    email: 'nora.mitchell@example.com',
    gender: 'Female',
    dateOfBirth: '2006-07-18',
    grade: 11,
    major: 'Engineering',
    enrollmentDate: '2022-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 94,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 80,
        completed: true,
      },
    ],
  },
  {
    id: 45,
    firstName: 'David',
    lastName: 'Carter',
    email: 'david.carter@example.com',
    gender: 'Male',
    dateOfBirth: '2005-01-29',
    grade: 12,
    major: 'Literature',
    enrollmentDate: '2021-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 78,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 97,
        completed: false,
      },
    ],
  },
  {
    id: 46,
    firstName: 'Aurora',
    lastName: 'Roberts',
    email: 'aurora.roberts@example.com',
    gender: 'Female',
    dateOfBirth: '2004-05-06',
    grade: 12,
    major: 'Chemistry',
    enrollmentDate: '2021-09-01',
    isActive: false,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 72,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 79,
        completed: true,
      },
    ],
  },
  {
    id: 47,
    firstName: 'Hunter',
    lastName: 'Gomez',
    email: 'hunter.gomez@example.com',
    gender: 'Male',
    dateOfBirth: '2006-06-28',
    grade: 11,
    major: 'Physics',
    enrollmentDate: '2022-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 86,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 90,
        completed: true,
      },
    ],
  },
  {
    id: 48,
    firstName: 'Stella',
    lastName: 'Ward',
    email: 'stella.ward@example.com',
    gender: 'Female',
    dateOfBirth: '2007-02-07',
    grade: 10,
    major: 'Computer Science',
    enrollmentDate: '2023-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 95,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 82,
        completed: false,
      },
    ],
  },
  {
    id: 49,
    firstName: 'Nathan',
    lastName: 'Brooks',
    email: 'nathan.brooks@example.com',
    gender: 'Male',
    dateOfBirth: '2005-08-15',
    grade: 12,
    major: 'Geography',
    enrollmentDate: '2021-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 76,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 92,
        completed: false,
      },
    ],
  },
  {
    id: 50,
    firstName: 'Lucy',
    lastName: 'Sanders',
    email: 'lucy.sanders@example.com',
    gender: 'Female',
    dateOfBirth: '2006-11-04',
    grade: 11,
    major: 'Science',
    enrollmentDate: '2022-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 100,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 96,
        completed: true,
      },
    ],
  },
  {
    id: 51,
    firstName: 'Thomas',
    lastName: 'Price',
    email: 'thomas.price@example.com',
    gender: 'Male',
    dateOfBirth: '2007-09-20',
    grade: 10,
    major: 'Math',
    enrollmentDate: '2023-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 96,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 88,
        completed: true,
      },
    ],
  },
  {
    id: 52,
    firstName: 'Paisley',
    lastName: 'Bennett',
    email: 'paisley.bennett@example.com',
    gender: 'Female',
    dateOfBirth: '2004-01-23',
    grade: 12,
    major: 'Biology',
    enrollmentDate: '2021-09-01',
    isActive: false,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 73,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 73,
        completed: true,
      },
    ],
  },
  {
    id: 53,
    firstName: 'Dylan',
    lastName: 'Wood',
    email: 'dylan.wood@example.com',
    gender: 'Male',
    dateOfBirth: '2006-05-31',
    grade: 11,
    major: 'Computer Science',
    enrollmentDate: '2022-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 77,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 84,
        completed: false,
      },
    ],
  },
  {
    id: 54,
    firstName: 'Naomi',
    lastName: 'Barnes',
    email: 'naomi.barnes@example.com',
    gender: 'Female',
    dateOfBirth: '2007-12-25',
    grade: 10,
    major: 'History',
    enrollmentDate: '2023-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 93,
        completed: true,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 93,
        completed: true,
      },
    ],
  },
  {
    id: 55,
    firstName: 'Caleb',
    lastName: 'Ross',
    email: 'caleb.ross@example.com',
    gender: 'Male',
    dateOfBirth: '2005-06-14',
    grade: 12,
    major: 'Science',
    enrollmentDate: '2021-09-01',
    isActive: true,
    courses: [
      {
        id: 1,
        name: 'Algebra',
        grade: 93,
        completed: false,
      },
      {
        id: 2,
        name: 'Biology',
        grade: 90,
        completed: false,
      },
    ],
  },
];

export const NEW_STUDENT: Student = {
  id: 0,
  firstName: '',
  lastName: '',
  email: '',
  gender: '',
  dateOfBirth: '',
  grade: Math.round(Math.random() * 10),
  major: '',
  enrollmentDate: '',
  courses: [],
  isActive: true,
};

export const COLLEGE_MAJORS: string[] = [
  'Computer Science',
  'Business Administration',
  'Mechanical Engineering',
  'Psychology',
  'Biology',
  'Economics',
  'Political Science',
  'Graphic Design',
];

export const COLLEGE_COURSES = [
  { id: 1, name: 'Algebra' },
  { id: 2, name: 'Biology' },
  { id: 3, name: 'Principles of Marketing' },
  { id: 4, name: 'Microeconomics' },
  { id: 5, name: 'Organic Chemistry' },
  { id: 6, name: 'World History' },
  { id: 7, name: 'Psychology of Learning' },
  { id: 8, name: 'Data Structures and Algorithms' },
  { id: 9, name: 'Statistics for Social Sciences' },
  { id: 10, name: 'Financial Accounting' },
  { id: 11, name: 'Modern Art and Design' },
  { id: 12, name: 'Environmental Science' },
  { id: 13, name: 'Artificial Intelligence' },
  { id: 14, name: 'Business Ethics' },
  { id: 15, name: 'Human Anatomy' },
  { id: 16, name: 'Introduction to Programming' },
  { id: 17, name: 'Calculus I' },
];
